In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
# Load the dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
# Drop irrelevant features
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data["Gender"] = label_encoder_gender.fit_transform(data["Gender"])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# OneHot Encode Geography
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geo = OneHotEncoder()
geo_encoder = one_hot_encoder_geo.fit_transform(data[["Geography"]])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [6]:
one_hot_encoder_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=one_hot_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
data = pd.concat([data.drop("Geography", axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
# Save the encoders and scaler
with open("label_encoder_gender.pkl", "wb") as outfile:
    pickle.dump(label_encoder_gender, outfile)

with open("one_hot_encoder_geo.pkl", "wb") as outfile:
    pickle.dump(one_hot_encoder_geo, outfile)

In [11]:
#Divide the dataset into independent and dependent features
X  = data.drop("Exited", axis=1)
Y = data["Exited"]

#Split the data into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

#Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [13]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [14]:
with open("scaler.pkl", "wb") as outfile:
    pickle.dump(scaler, outfile)

### ANN Implementation

In [15]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\pushpit\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (72.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\pushpit\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pushpit\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pushpit\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pushpit\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pushpit\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\pushpit\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\pushpit\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in c:\users\pushpit\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\pushpit\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\pushpit\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pushpit\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\pushpit\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential # Neural Network
from tensorflow.keras.layers import Dense # To create neurons
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [17]:
X_train.shape

(8000, 12)

In [18]:
## Build ANN Model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), # HL1. 64 hidden neurons, 12 input nodes fed as we have 12 columns. We just need to do this for first hiddent layer
    Dense(32, activation='relu'), # HL2
    Dense(1, activation='sigmoid') # Output Layer  
] 
)

C:\Users\Pushpit\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │             832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
## Compile Model
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.BinaryCrossentropy()
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [21]:
# Set up the TensorBoard to capture and visulize logs
logs_dir = 'logs/fit' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [22]:
pip install TensorBoard

Requirement already satisfied: TensorBoard in c:\users\pushpit\anaconda3\lib\site-packages (2.20.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: absl-py>=0.4 in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (3.8)
Requirement already satisfied: numpy>=1.12.0 in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (2.1.3)
Requirement already satisfied: packaging in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (24.2)
Requirement already satisfied: pillow in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (11.3.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (7.34.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (72.1.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\pushpit\anaconda3\lib\site-packages (from TensorBoard) (3.1.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\pushpit\anaconda3\lib\site-packages (from grpcio>=1.48.2->TensorBoard) (4.12.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\pushpit\anaconda3\lib\site-packages (from werkzeug>=1.0.1->TensorBoard) (3.0.2)

In [23]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
tensorflow_callback = TensorBoard(log_dir=logs_dir, histogram_freq=1)

In [24]:
# Set up Early Stopping. We can train a Neural Network for as many epochs as we want. But if we achieve best performance at early stages then we should stop training the neural network further.
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True) # Wait for at least 5 epochs before checking for EarlyStopping

In [25]:
## Train the model
history = model.fit(
    X_train,Y_train,validation_data=(X_test,Y_test),
    epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8361 - loss: 0.3890 - val_accuracy: 0.8525 - val_loss: 0.3501
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8545 - loss: 0.3534 - val_accuracy: 0.8490 - val_loss: 0.3631
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8586 - loss: 0.3462 - val_accuracy: 0.8550 - val_loss: 0.3647
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8587 - loss: 0.3468 - val_accuracy: 0.8600 - val_loss: 0.3551
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8608 - loss: 0.3375 - val_accuracy: 0.8600 - val_loss: 0.3445
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8622 - loss: 0.3390 - val_accuracy: 0.8555 - val_loss: 0.3482
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8602 - loss: 0.3382 - val_accuracy: 0.8600 - val_loss: 0.3478
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8608 - loss: 0.3348 - val_accuracy: 0.8625 - val_loss: 0.3350
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3310 - val_accuracy: 0.8605 - val_loss: 0.3530
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8643 - loss: 0.3293 - val_accuracy: 0.8595 - val_loss: 0.3456
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8626 - loss: 0.3299 - val_accuracy: 0.8600 - val_loss: 0.3446
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3262 - val_accuracy: 0.8570 - val_loss: 0.3385
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8649 - loss: 0.3237 - val_accuracy: 0.8585 - val_loss: 0.3462
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8666 - loss: 0.3234 - val_accuracy: 0.8600 - val_loss: 0.3403
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8699 - loss: 0.3199 - val_accuracy: 0.8630 - val_loss: 0.3371
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8708 - loss: 0.3155 - val_accuracy: 0.8550 - val_loss: 0.3583
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8692 - loss: 0.3199 - val_accuracy: 0.8605 - val_loss: 0.3500
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8701 - loss: 0.3155 - val_accuracy: 0.8550 - val_loss: 0.3603

In [26]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [27]:
# Load TensorBoard extension
%load_ext tensorboard

In [31]:
%tensorboard --logdir logs/fit20260502-124616

In [ ]:
## Load the pickle file